experiment:
  name: ''
  description: 噪声参数对比实验
  author: researcher
  version: '1.0'
data:
  root: /mnt/e/data/liuyang/original_202507
  input_subdir: 04_original_data_no_editing_processed/post_surgery/RestTARWSDCF
  output_base_subdir: 04_noisy_data_no_editing_processed/post_surgery/RestTARWSDCF
mni_coordinates:
- name: whole
  description: 避开DMN, SN, CEN网络节点的完整坐标集
  coordinates:
  - [-18, 24, 53]
  - [22, 26, 51]
  - [-18, -1, 65]
  - [20, 4, 64]
  - [-27, 43, 31]
  - [30, 37, 36]
  - [-42, 13, 36]
  - [42, 11, 39]
  - [-28, 56, 12]
  - [28, 55, 17]
  - [-41, 41, 16]
  - [42, 44, 14]
  - [-33, 23, 45]
  - [42, 27, 39]
  - [-32, 4, 55]
  - [34, 8, 54]
  - [-26, 60, -6]
  - [25, 61, -4]
  - [-65, -30, -12]
  - [65, -29, -13]
  - [-53, 2, -30]
  - [51, 6, -32]
  - [-59, -58, 4]
  - [60, -53, 3]
  - [-58, -20, -9]
  - [58, -16, -10]
  - [-27, -7, -34]
  - [28, -8, -33]
  - [-25, -25, -26]
  - [26, -23, -27]
  - [-28, -32, -18]
  - [30, -30, -18]
  - [-19, -12, -30]
  - [19, -10, -30]
  - [-23, 2, -32]
  - [22, 1, -36]
  - [-17, -39, -10]
  - [19, -36, -11]
  - [-16, -60, 63]
  - [19, -57, 65]
  - [-27, -59, 54]
  - [31, -54, 53]
  - [-34, -80, 29]
  - [45, -71, 20]
  - [-38, -61, 46]
  - [39, -65, 44]
  - [-51, -33, 42]
  - [47, -35, 45]
  - [-56, -49, 38]
  - [57, -44, 38]
  - [-47, -65, 26]
  - [53, -54, 25]
  - [-53, -31, 23]
  - [55, -26, 26]
  - [-5, -63, 51]
  - [6, -65, 51]
  - [-8, -47, 57]
  - [7, -47, 58]
  - [-12, -67, 25]
  - [16, -64, 25]
  - [-6, -55, 34]
  - [6, -54, 35]
  - [-36, -20, 10]
  - [37, -18, 8]
  - [-32, 14, -13]
  - [33, 14, -13]
  - [-34, 18, 1]
  - [36, 18, 1]
  - [-38, -4, -9]
  - [39, -2, -9]
  - [-38, -8, 8]
  - [39, -7, 8]
  - [-38, 5, 5]
  - [38, 5, 5]
  - [-4, -39, 31]
  - [4, -37, 32]
  - [-3, 8, 25]
  - [5, 22, 12]
  - [-6, 34, 21]
  - [5, 28, 27]
  - [-8, -47, 10]
  - [9, -44, 11]
  - [-5, 7, 37]
  - [4, 6, 38]
  - [-7, -23, 41]
  - [6, -20, 40]
  - [-4, 39, -2]
  - [5, 41, 6]
  - [-19, -2, -20]
  - [19, -2, -19]
  - [-27, -4, -20]
  - [28, -3, -20]
  - [-22, -14, -19]
  - [22, -12, -20]
  - [-28, -30, -10]
  - [29, -27, -10]
  - [-7, -12, 5]
  - [7, -11, 6]
  - [-18, -13, 3]
  - [12, -14, 1]
  - [-18, -23, 4]
  - [18, -22, 3]
  - [-7, -14, 7]
  - [3, -13, 5]
  - [-16, -24, 6]
  - [15, -25, 6]
  - [-15, -28, 4]
  - [13, -27, 8]
  - [-12, -22, 13]
  - [10, -14, 14]
  - [-11, -14, 2]
  - [13, -16, 7]
parameters:
  avoid_radius:
    values:
    - 12
    description: 保护区域半径，单位毫米
  noise_params:
  - name: low_noise
    params:
      mean: 0
      std: 25
    description: 低强度高斯噪声
  - name: high_noise
    params:
      mean: 0
      std: 100
    description: 高强度高斯噪声
processing:
  noise_type: gaussian
  save_mask: false
  use_brain_mask: true
execution:
  max_workers: 4
  skip_existing: true
  save_intermediate: true
  max_subjects: null
output:
  save_config: true
  save_csv: true
  save_json: true
  generate_report: true
logging:
  level: INFO
  console_output: true
  file_output: true
advanced:
  memory_limit_gb: 8
  max_retries: 3
  retry_delay: 5
  monitor_memory: true
  monitor_cpu: true
  backup_original: false
extensions:
  custom_validators: []
  post_processors: []
  plugins: []
